### PR TITLE
move gradient_checkpointing over to training_arguments since it's now…

### PR DESCRIPTION
**Pull request by dlwh**
… baked into HF.

## Description

gradient_checkpointing was special cased in auto_clm, but it's now natively supported by HuggingFace in TrainingArguments, so may as well move it in there.

## Unit test coverage

I made sure the deprecation warning did the expected thing.

## Known breaking changes/behaviors

Deprecates rather than removes gradient_checkpointing from the model config, so I don't think it should break anything.

### CODE REVIEW

**Comment by siddk** [comment]
This makes sense to me; do we need to bump the Transformers dependency or is it supported in current repo version (as in the environment.yaml)?

**Comment by dlwh** [comment]
It went in in https://github.com/huggingface/transformers/releases/tag/v4.11.0. The checked in env yaml files depend on either the github repo directly (which seems non-ideal) or on 4.12.3, so we're good.

**Comment by siddk** [comment]
Sweet; let's wait for tests to pass, then feel free to merge.

**Review by siddk — APPROVED** [review]
LGTM

**Comment by dlwh** [comment]
iirc I think @J38 said tests aren't running right now?

**Pull request merged**
