### PR TITLE
remove old _get_train_sampler since the relevant changes have been upstreamed

### PR DESCRIPTION
**Pull request by dlwh**
## Description
After reviewing the code, I think we can safely remove this change. (My preference is to remove stuff like this when possible because of staleness w.r.t. upstream).

Here's the diff against transformers/master:

https://editor.mergely.com/F7Ta6e2R/

## Known breaking changes/behaviors
None

### CODE REVIEW

**Comment by dlwh** [comment]
I guess should add I have a PR to make a change to this same method in transformers at https://github.com/huggingface/transformers/pull/15961 but I don't think that should impact us removing the override here.

**Comment by dlwh** [comment]
Ok, so this fails the test, but IMHO the test as written isn't what we should be enforcing unless we want to preserve the order for all time. It's better imho to enforce the invariant we want (the same seed produces the data in the same order, different seeds in different orders)

WDYT?

**Comment by J38** [comment]
That sounds good I can update it to match your request.

**Comment by dlwh** [comment]
I already updated the test, just haven't pushed yet. Give me a sec and it'll be up there

**Comment by dlwh** [comment]
fwiw, i think the upstream changes I've PR'ed to HF will make this even better and I believe would make the current test as it's coded pass (if we add the new seed parameter).

**Comment by dlwh** [comment]
actually my test doesn't work until the new changes are merged into HF transformers. Could also resolve by fixing ordering with the training data loaders (https://github.com/huggingface/transformers/pull/15961#issuecomment-1061026744 is the problem)

**Comment by dlwh** [comment]
i verified that the test_seed test now passes on my machine. I'm inclined to merge because the queue is still broken.

**Pull request merged**
