### PR TITLE
Fork Preprocessing when doing multiple gpus

### LINKED ISSUE #117: Tokenization crashes when using deepspeed
**Describe the bug**

via @J38 in #109 :" tokenization crashes when using deepspeed" 

We should either refactor entry point to run data processing and then call launcher with subprocess after data has been processed

Or, better, stream data #116 

**To Reproduce**
Steps to reproduce the bug. TODO

**Expected behavior**
don't crash

**Additional context**

related to #116

### PR DESCRIPTION
**Pull request by dlwh**
Fixes #117

So, as hypothesized in #126  by @jthickstun, parallelized preprocessing was leading to major problems, particularly as one added more GPUs. To mitigate this, I've now made it so that preprocessing is forked into a single separate process per-machine (I'm assuming we're using local file systems for caches)

### CODE REVIEW

**Comment by dlwh** [comment]
@J38 ping

**Comment by J38** [comment]
In terms of the code this seems fine to me if we want to go with this approach!

**Comment by J38** [comment]
In terms of the code this seems fine to me if we want to go with this approach!

**Comment by J38** [comment]
I will say I have one quibble with this approach ... I am concerned (but not outright opposed) with having the data pre-processing be within the deepspeed launcher call and the general complexity of the various processes communication when what we simply want is "don't run a bunch of data pre-processing calls" ... we may wish we had opted for a simpler process of 1. data pre-process 2. deepspeed the training stuff ... it is possible this will be fine and we'll never worry about it again ... but it is also possible we'll end up with a bunch of weird hangs because of some bug/issue involved with the process communication and wish we had opted for a simpler set up ... there is something to be said for a new set up that is basically just 1. run the data pre-processing without deepspeed 2. use the deepspeed launcher just for the GPU training stuff ...

**Comment by J38** [comment]
I will say I have one quibble with this approach ... I am concerned (but not outright opposed) with having the data pre-processing be within the deepspeed launcher call and the general complexity of the various processes communication when what we simply want is "don't run a bunch of data pre-processing calls" ... we may wish we had opted for a simpler process of 1. data pre-process 2. deepspeed the training stuff ... it is possible this will be fine and we'll never worry about it again ... but it is also possible we'll end up with a bunch of weird hangs because of some bug/issue involved with the process communication and wish we had opted for a simpler set up ... there is something to be said for a new set up that is basically just 1. run the data pre-processing without deepspeed 2. use the deepspeed launcher just for the GPU training stuff ...

**Comment by dlwh** [comment]
i think that's reasonable. i'm a bit wary of all that just because so much of the way people are told/trained to use deepspeed (and torch distributed launch) is to use the launcher script at top level, I'm not sure it will behave if we do an internal fork. if we want to explicitly have two phases you have to run, that's fine too (and pretty trivial to support with the new code)

**Pull request merged**
