### PR TITLE
add pre-commit action, run pre-commit

### PR DESCRIPTION
**Pull request by dlwh**
Honestly I could go either way on this, but it seems like we wanted to use pre-commit hooks (since there's a config) so seems like we should enforce it and add a hook.

### CODE REVIEW

**Comment by siddk** [comment]
So semi-hot take; I don't like pre-commit as a Github Action - it'll actually change code after each push, requiring you to pull/refresh.

I like having a pre-commit option for folks to install locally to keep their commits clean, but as an action, I think we should only run the fixed style check (`make style`)

**Comment by dlwh** [comment]
i thought this was just the style check where it fails if it's not clean? but i dunno. I agree it shouldn't be pushing commits.

**Comment by dlwh** [comment]
fwiw, it didn't like my first push, and just errored out. it didn't change my code

**Comment by siddk** [comment]
Because Flake failed -- looks like you were already Black/isort ready: https://github.com/stanford-crfm/mistral/runs/6317600080?check_suite_focus=true

**Comment by dlwh** [comment]
I'm pretty sure it won't push changes unless you give it a token: https://github.com/pre-commit/action/blob/main/index.js#L49 and we can just not give it a token. 

Also take a look at the latest run...

**Comment by dlwh** [comment]
i'll be honest i basically dislike formatting linters, but imho if we're going to have it we should be enforcing it so we don't get noise in PRs from people who turn it on due to people who commit with it off

**Review by Skylion007 — DISMISSED** [review]

**Comment by dlwh** [comment]
Take a look at https://github.com/pre-commit/action/#using-this-action-in-private-repositories. turns out they removed the auto-commit "feature" so i'm gonna update to that.

**Comment by dlwh** [comment]
i got the verbal ok from @siddk so i'm gonna merge.

**Pull request merged**
